// Golden test: run the userscript's pure converter on a real serialized
// ResGameRecord fixture and assert its tenhou `log` matches the frozen expected
// output. The fixture was generated by a pipeline validated round-for-round
// against tensoul-py. Run with `npm test` (or `node test/run.cjs`).
"use strict";
const fs = require("fs");
const path = require("path");

// Load the userscript in a minimal shim so its IIFE exposes window.__majsoulNaga.
const win = {};
global.window = win;
global.document = { addEventListener() {} };
console.log = () => {};
const script = fs.readFileSync(path.join(__dirname, "..", "majsoul-naga.user.js"), "utf8");
eval(script);
console.log = require("console").log; // restore for our own output

const fx = path.join(__dirname, "fixtures");
const bytes = new Uint8Array(Buffer.from(fs.readFileSync(path.join(fx, "sample.res.b64"), "utf8"), "base64"));
const got = win.__majsoulNaga.recordToTenhou(bytes).log;
const expected = JSON.parse(fs.readFileSync(path.join(fx, "sample.expected.json"), "utf8"));

function deepEqual(a, b) {
  return JSON.stringify(a) === JSON.stringify(b);
}

if (!deepEqual(got, expected)) {
  console.error("FAIL: converter output does not match fixture");
  for (let i = 0; i < Math.max(got.length, expected.length); i++) {
    if (JSON.stringify(got[i]) !== JSON.stringify(expected[i])) {
      console.error(
        `  round ${i}\n    got: ${JSON.stringify(got[i])}\n    exp: ${JSON.stringify(expected[i])}`,
      );
    }
  }
  process.exit(1);
}

// sanity: per-round NAGA payload split
const payload = win.__majsoulNaga.toNagaCustom({
  title: ["", ""],
  name: ["", "", "", ""],
  rule: {},
  log: got,
});
if (payload.length !== got.length) {
  console.error("FAIL: NAGA payload split mismatch");
  process.exit(1);
}

// kiriage mangan must use tenhou's plain fu/han label; NAGA rejects "切り上げ満貫"
const kiriage = win.__majsoulNaga.scoreString({
  tsumo: true,
  oya: false,
  han: 4,
  fu: 30,
  point: { tsumo: 2000, tsumo_oya: 4000, ron: 0, oya: false },
});
if (kiriage !== "30符4飜2000-4000点") {
  console.error(`FAIL: kiriage score string: ${kiriage}`);
  process.exit(1);
}

console.error(`ok - converter matches fixture (${got.length} rounds)`);
